spring.application.name=petshop2026
spring.config.import=optional:file:./.env[.properties]
spring.profiles.default=none
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
