--liquibase formatted sql

--changeset vinicius:001-tutor
CREATE TABLE tutor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    email VARCHAR(160) NOT NULL UNIQUE,
    telefone VARCHAR(20) NOT NULL
);

--changeset vinicius:002-pet
CREATE TABLE pet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(80) NOT NULL,
    especie VARCHAR(20) NOT NULL CHECK (especie IN ('CACHORRO', 'GATO')),
    raca VARCHAR(80) NOT NULL,
    tutor_id BIGINT NOT NULL REFERENCES tutor(id)
);
CREATE INDEX idx_pet_tutor ON pet(tutor_id);

--changeset vinicius:003-atendimento
CREATE TABLE atendimento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(60) NOT NULL UNIQUE,
    pet_id BIGINT NOT NULL REFERENCES pet(id),
    servico VARCHAR(20) NOT NULL CHECK (servico IN ('BANHO', 'TOSA', 'BANHO_E_TOSA')),
    data_hora TIMESTAMP NOT NULL,
    valor NUMERIC(10,2) NOT NULL CHECK (valor > 0),
    status VARCHAR(20) NOT NULL CHECK (status IN ('AGENDADO', 'CONCLUIDO'))
);
CREATE INDEX idx_atendimento_pet ON atendimento(pet_id);
